di_bridge:
    enable_cache: false
    extensions:
        - { name: 'Teknoo\East\FoundationBundle\Extension\PHPDI', priority: 0 }
    definitions:
        - { priority: 0, file: '%kernel.project_dir%/config/di.hook.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.variables.east.common.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.variables.east.paas.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.variables.from.envs.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.variables.kubernetes.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.variables.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.common.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.persisted_vars.encryption.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.persistent_data.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.recipe.steps.php' }
        - { priority: 0, file: '%kernel.project_dir%/config/di.recipe.plans.php' }

when@prod:
    di_bridge:
        enable_cache: false
        compilation_path: '%kernel.project_dir%/var/cache/prod/phpdi'

when@test:
    di_bridge:
        enable_cache: false
        compilation_path: '%kernel.project_dir%/var/cache/test/phpdi'
