di_bridge:
    definitions:
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/src/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Doctrine/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Flysystem/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Git/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Kubernetes/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Image/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/ProjectBuilding/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Laminas/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/PhpSecLib/di.php' }
       - { priority: 10, file: '%kernel.project_dir%/vendor/teknoo/east-paas/infrastructures/Symfony/Components/di.php' }