framework:
    #esi: ~
    secret: '%env(APP_SECRET)%'
    form: ~
    csrf_protection: ~
    serializer: ~
    property_info:
        enabled: true
    trusted_hosts: ~
    session:
        cookie_lifetime: 36000
        cookie_path: '/'
        cookie_domain: ''
        cookie_httponly: true
        cookie_secure: true
        cookie_samesite: "lax"
        gc_probability: 5
        gc_maxlifetime: 3600
    fragments: ~
    http_method_override: true
    handle_all_throwables: true
    annotations:
        enabled: false
    php_errors:
        log: true
    router:
        default_uri: 'https://%env(SPACE_HOSTNAME)%/'