# config/packages/html_sanitizer.yaml
framework:
    html_sanitizer:
        sanitizers:
            default:
                allow_safe_elements: true
                allow_static_elements: true
                force_https_urls: true
                allowed_link_schemes: ['https']
                allow_relative_links: true
                allowed_media_schemes: [ 'http', 'https', 'mailto' ]
                allowed_media_hosts: [ 'teknoo.software', 'teknoo.net' ]
                allow_relative_medias: true
                allow_elements:
                    img: 'src'
                allow_attributes:
                    src: ['img']
                    data-attr: '*'
                    id: '*'
                    style: '*'
