lexik_jwt_authentication:
    secret_key: '%env(resolve:SPACE_JWT_SECRET_KEY)%'
    public_key: '%env(resolve:SPACE_JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(SPACE_JWT_PASSPHRASE)%'
    token_ttl: '%env(int:SPACE_JWT_TTL)%'
    token_extractors:
        query_parameter:
            enabled: '%teknoo.space.jwt.enable_in-query%'
            name: bearer
