framework:
    messenger:
        transports:
            new_task:
                dsn: '%teknoo.space.messenger.dsn.new_task%'
                retry_strategy:
                    max_retries: 3
        routing:
            Teknoo\Space\Contracts\DTO\NewTaskInterface: 'new_task'

when@test:
    framework:
        messenger:
            transports:
                new_task:
                    dsn: 'test://?support_delay_stamp=true'
                    retry_strategy:
                        max_retries: 0
