# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    # Google Authenticator config
    google:
        enabled: true                           # If Google Authenticator should be enabled, default false
        server_name: '%env(SPACE_HOSTNAME)%'  # Server name used in QR code
        issuer: Teknoo Space                    # Issuer name used in QR code
        leeway: 1                               # How many codes before/after the current one would be accepted as valid
        template: '@TeknooEastCommon/2fa/login.html.twig'

    totp:
        enabled: true                           # If TOTP authentication should be enabled, default false
        server_name: '%env(SPACE_HOSTNAME)%'  # Server name used in QR code
        issuer: Teknoo Space                    # Issuer name used in QR code
        leeway: 1                               # How many codes before/after the current one would be accepted as valid
        parameters:                             # Additional parameters added in the QR code
            image: 'https://teknoo.software/img/logo.svg'
        template: '@TeknooEastCommon/2fa/login.html.twig'