twig:
    exception_controller: null
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        languagesList: '%languages%'
        formFactory: '@form.factory'
        authenticationUtils: '@Symfony\Component\Security\Http\Authentication\AuthenticationUtils'
        mercureUrl: '%env(MERCURE_SUBSCRIBER_URL)%'
        mercureEnabled: '%teknoo.space.mercure.publishing_enabled%'