services:
    db:
        build:
            args:
                MONGO_VERSION: 4
    mercure:
        environment:
            - MERCURE_PUBLISHER_JWT_KEY=3Rnh4FmrdGzHgNGooXAgPNr7D3GzAge6eDegcj5egX7iQopys8f4mM9AYSMDLc
            - MERCURE_SUBSCRIBER_JWT_KEY=3Rnh4FmrdGzHgNGooXAgPNr7D3GzAge6eDegcj5egX7iQopys8f4mM9AYSMDLc
    web:
        environment:
            - APP_ENV=dev
            - APP_REMEMBER_SECRET=013a01183dac9d12bb62112c5f707f71
            - APP_SECRET=47fc53f0b1c436cf387c68832e5fdd5d
            - MAILER_DSN=smtp://space%40teknoo.software:o%21%21Ddp5yYRTkBGEK@pro1.mail.ovh.net:587
            - MAILER_REPLY_TO_ADDRESS=space@teknoo.software
            - MAILER_SENDER_ADDRESS=space@teknoo.software
            - MERCURE_JWT_TOKEN=3Rnh4FmrdGzHgNGooXAgPNr7D3GzAge6eDegcj5egX7iQopys8f4mM9AYSMDLc
            - MERCURE_PUBLISH_URL=http://mercure:8181/.well-known/mercure
            - MERCURE_SUBSCRIBER_URL=https://localhost/hub/.well-known/mercure
            - MESSENGER_NEW_JOB_DSN=amqp://space:space_pwd@amqp:5672/%2f/new_job
            - MONGODB_SERVER=mongodb://space_user:space_pwd@db/teknoo_space
            - OAUTH_DO_CLIENT_ID=
            - OAUTH_DO_CLIENT_SECRET=
            - OAUTH_CLIENT_ID=
            - OAUTH_CLIENT_SECRET=
            - OAUTH_GH_CLIENT_ID=
            - OAUTH_GH_CLIENT_SECRET=
            - OAUTH_GITLAB_CLIENT_ID=a84c2e34b14ac311378ad4fba1b324b820c03c463df0ce97f357ca79256b2475
            - OAUTH_GITLAB_CLIENT_SECRET=gloas-945e19c7ffd00dad700e3031836dd2a27879998e7ea351911f16ac34cf4ad51d
            - OAUTH_GITLAB_SERVER_URL=https://gitlab.teknoo.software/
            - OAUTH_GOOGLE_CLIENT_ID=
            - OAUTH_GOOGLE_CLIENT_SECRET=
            - OAUTH_JIRA_CLIENT_ID=
            - OAUTH_JIRA_CLIENT_SECRET=
            - OAUTH_MS_CLIENT_ID=
            - OAUTH_MS_CLIENT_SECRET=
            - OAUTH_ENABLED=1
            - OAUTH_SERVER_TYPE=gitlab
            - SPACE_2FA_PROVIDER=google_authenticator
            - SPACE_CODE_GENERATOR_SALT=v8QMHBgyHwv/j2nPqcghDA0I5O5Q1MsJFckLSkQFEW2uSEEi0FXKEfFxkkUap66uEHG4aNAXLy59SDIzme4OFMH2sio7QQZrDtgpbX
            - SPACE_JWT_ENABLE_IN_QUERY=0
            - SPACE_JWT_MAX_DAYS_TO_TIVE=30
            - SPACE_JWT_PASSPHRASE=ajpQepxkoX7LTCP3m44g8GKLd8FHLgAdp86Jn7nTJNgm9dXgjfb68mnG7f7xH3cA
            - SPACE_OCI_GLOBAL_REGISTRY_PWD=a55R@JbJL&5eS53$$
            - SPACE_OCI_GLOBAL_REGISTRY_URL=registry.hydrogen.teknoo.net
            - SPACE_OCI_REGISTRY_URL=.registry.hydrogen.teknoo.net
            - SPACE_PERSISTED_VAR_SECURITY_ALGORITHM=rsa
            - SPACE_PERSISTED_VAR_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/variables/public.pem
            - SPACE_SUBSCRIPTION_DEFAULT_PLAN=hydrogen-small
            - SPACE_SUPPORT_CONTACT=support@teknoo.space
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/messages/public.pem
            - PHP_XDEBUG_HOST=172.16.1.1
            - |
              SPACE_SUBSCRIPTION_PLAN_CATALOG_JSON=[
                  {
                      "id": "hydrogen-small",
                      "name": "Hydrogen Plan Small",
                      "envsCountAllowed": 1,
                      "quotas": [
                          {
                              "category": "compute",
                              "type": "cpu",
                              "capacity": "1",
                              "requires": "1"
                          },
                          {
                              "category": "memory",
                              "type": "memory",
                              "capacity": "512Mi",
                              "requires": "512Mi"
                          }
                      ],
                      "clusters": ["Teknoo Space Hydrogen"]
                  },
                  {
                      "id": "hydrogen-standard",
                      "name": "Hydrogen Plan Standard",
                      "envsCountAllowed": 2,
                      "projectsCountAllowed": 3,
                      "quotas": [
                          {
                              "category": "compute",
                              "type": "cpu",
                              "capacity": "1.5",
                              "requires": "1.5"
                          },
                          {
                              "category": "memory",
                              "type": "memory",
                              "capacity": "1Gi",
                              "requires": "1Gi"
                          }
                      ],
                      "clusters": ["Teknoo Space Hydrogen"]
                  },
                  {
                      "id": "hydrogen-large",
                      "name": "Hydrogen Plan Large",
                      "envsCountAllowed": 2,
                      "projectsCountAllowed": 4,
                      "quotas": [
                          {
                              "category": "compute",
                              "type": "cpu",
                              "capacity": "2",
                              "requires": "2"
                          },
                          {
                              "category": "memory",
                              "type": "memory",
                              "capacity": "1.5Gi",
                              "requires": "1.5Gi"
                          }
                      ],
                      "clusters": ["Teknoo Space Hydrogen"]
                  }
                ]
            - |
              SPACE_CLUSTER_CATALOG_JSON=[
                  {
                      "master": "https://hydrogen.teknoo.net:16443",
                      "dashboard": "https://dashboard.hydrogen.teknoo.net/",
                      "create_account": {
                          "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6InB3Y1Vla0N5LVZmUkdYTGR3V1hVRjdhT2xTREYxbEFjRlExMFFNT0JzcUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzcGFjZS1hcHAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYWRtaW4tY3JlYXRlLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLWNyZWF0ZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjA1NjJlYjQzLTdmM2QtNDI4My1hOTlhLWI2MWUxNzcxMzM3YiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzcGFjZS1hcHA6YWRtaW4tY3JlYXRlIn0.UQBO6C6YLfML4rMhxMeiJOpf3_fdzRBbhDPdBYayQ47b1arrjqaeKrE7wiN30ch0PoIId0VIjRF_gPyYQh04sLrjAmVe3p1q5AkFtkp0b-9xJnvGqvnQWiL8XrPrJO_YGmz_8R59d9PRzorabOHeD6_CMYnd8XlPnNhvKEX0DPwTLMSB-ZqojGdt8s9SNupwb8bhnHydmffNSSDph8O2TC4qxSo7EK552A2A8_ZOFTkCsZfLIaju7pRfcIRDgRbtuCB1-4BPIm0hScz_2mvASglLz-B-3a44asknbPkhGSf75cH1g8ZIOWlyMwEe2atZQD-XVT6_n9FRN7TTxzBmJw",
                          "ca_cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWVJJMERSZTRlN09DcTdkL21IcFNGemVtcVdvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSTBNRFV6TVRBNE5EWXpNVm9YRFRNMApNRFV5T1RBNE5EWXpNVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2Q0NhSklrWHM4dWo4TDUrMzN4aXF4azB2SU1JQXY1Vys3eHEKT21nNlNjdks3RXVoZWd1bUN6WERpY052aDFSNnNXc1hCZ1JOWitVVkVNSHBkZC9ma3ZudmsxOTNyWTUxcFhGQgpxQjFvYTA1S2NvaXJ2N0FjTHhJSEJxQmdyeFdPOGdUVHpGVTk4QlhnNkFpa3dzQnVpMXpwSTIwVUNxa0xNejNLCnlqc01lYklqVjZZK0RIWWhrSDRMU0xQVENZa1NOUDZYbHhBYWpHUjZvUXE2YWVCRURpQ3JMcllKVkVDSklrck0KcmhnVmR3R1M3U0lleGNaYTg2V29IM2daREFncTNYR252MGJCd2czZTEwS0pqN3VtbUF1ckpMb3gyYm5XUktNMwpORWVnSE5lM1c1OTg3TG94S2I0TndMNlQ5b2lNMGtESDdNUU1jcTZFV1VSRUh0TUlid0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWRnU1RrQW5YRk9HbU52Qm9NajFJL01Sc1MyY3dId1lEVlIwakJCZ3dGb0FVZGdTVGtBblgKRk9HbU52Qm9NajFJL01Sc1MyY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBWVJoRmQ1M1RESUQzUjFHcXFQTnc2dXFsdzJaaWd3eHo1MCs4d3gwVFNDVjQwSHZuN0tKZ1JyUSs5NUFBClhGUTRHQ1JCZEc2WVVUaGZOZzdKOE8yVThYN0sxZ01mdmxtK0tWbmJWeGtLWk9uYmF3QnVqZlpsYTB6MDN0LzYKbk5BRmFrWkpzeG9lbXFnWGhObnhCMHZoWGp5WEM2Q2IxODI2OG1mcGJNTWVZcmdDajVGYWpLdmJ3ZlVCNXRxNwo5WDVRMXRBdE1uMXlEd1JDeWtvOWxFNk1GZTloSE1Db3JFSWdvdEc4aUUvMyttUFQwRFRzcGdncWJVYmlEK3R3Ci9QY3pZNW1ZL2twRHByTXd2VFN5MFFnS0I0MW9ZS3U1T2VLRzlPVnJnRFRQT2R3eG11dVFmWVBGanlDMTNiTGYKdnM3NlV2eGxmRlJLNUtYRVRzamVBRnJkakE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
                      },
                      "name": "Teknoo Space Hydrogen",
                      "type": "kubernetes",
                      "storage_provisioner": "nfs.csi.k8s.io",
                      "support_registry": true,
                      "use_hnc": false
                  },
                  {
                      "master": "https://helium.teknoo.net:16443",
                      "dashboard": "https://dashboard.helium.teknoo.net/",
                      "create_account": {
                          "token": "foo",
                          "ca_cert": "bar"
                      },
                      "name": "Teknoo Space Helium",
                      "type": "kubernetes",
                      "storage_provisioner": "nfs.csi.k8s.io",
                      "support_registry": true,
                      "use_hnc": false
                  }
                ]
    cli_new_job:
        environment:
            - APP_ENV=dev
            - APP_SECRET=47fc53f0b1c436cf387c68832e5fdd5d
            - MERCURE_JWT_TOKEN=3Rnh4FmrdGzHgNGooXAgPNr7D3GzAge6eDegcj5egX7iQopys8f4mM9AYSMDLc
            - MERCURE_PUBLISH_URL=http://mercure:8181/.well-known/mercure
            - MERCURE_SUBSCRIBER_URL=https://localhost/hub/.well-known/mercure
            - MESSENGER_EXECUTE_JOB_DSN=amqp://space:space_pwd@amqp:5672/%2f/execute_job
            - MESSENGER_HISTORY_SENT_DSN=amqp://space:space_pwd@amqp:5672/%2f/history_sent
            - MONGODB_SERVER=mongodb://space_user:space_pwd@db/teknoo_space
            - SPACE_JWT_PASSPHRASE=ajpQepxkoX7LTCP3m44g8GKLd8FHLgAdp86Jn7nTJNgm9dXgjfb68mnG7f7xH3cA
            - SPACE_PERSISTED_VAR_SECURITY_ALGORITHM=rsa
            - SPACE_PERSISTED_VAR_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/variables/private.pem
            - SPACE_PERSISTED_VAR_SECURITY_PRIVATE_KEY_PASSPHRASE=KHHyy?l&IHNLc1L#UDRX!3@pFP0304EVcd0fq?MT
            - SPACE_PERSISTED_VAR_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/variables/public.pem
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/messages/private.pem
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY_PASSPHRASE=GQRNrqcX9fkAAHSg8P6MKktykTh399
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/messages/public.pem
            - PHP_XDEBUG_HOST=172.16.1.1
    cli_job_done:
        environment:
            - APP_ENV=dev
            - APP_SECRET=47fc53f0b1c436cf387c68832e5fdd5d
            - MESSENGER_JOB_DONE_DSN=amqp://space:space_pwd@amqp:5672/%2f/job_done
            - MONGODB_SERVER=mongodb://space_user:space_pwd@db/teknoo_space
            - SPACE_JWT_PASSPHRASE=ajpQepxkoX7LTCP3m44g8GKLd8FHLgAdp86Jn7nTJNgm9dXgjfb68mnG7f7xH3cA
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/messages/private.pem
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY_PASSPHRASE=GQRNrqcX9fkAAHSg8P6MKktykTh399
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/messages/public.pem
            - PHP_XDEBUG_HOST=172.16.1.1
    cli_history_sent:
        environment:
            - APP_ENV=dev
            - APP_SECRET=47fc53f0b1c436cf387c68832e5fdd5d
            - MESSENGER_HISTORY_SENT_DSN=amqp://space:space_pwd@amqp:5672/%2f/history_sent
            - MONGODB_SERVER=mongodb://space_user:space_pwd@db/teknoo_space
            - SPACE_JWT_PASSPHRASE=ajpQepxkoX7LTCP3m44g8GKLd8FHLgAdp86Jn7nTJNgm9dXgjfb68mnG7f7xH3cA
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/messages/private.pem
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY_PASSPHRASE=GQRNrqcX9fkAAHSg8P6MKktykTh399
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/messages/public.pem
            - PHP_XDEBUG_HOST=172.16.1.1
    cli_execute:
        environment:
            - APP_ENV=dev
            - APP_SECRET=47fc53f0b1c436cf387c68832e5fdd5d
            - MESSENGER_EXECUTE_JOB_DSN=amqp://space:space_pwd@amqp:5672/%2f/execute_job
            - MESSENGER_HISTORY_SENT_DSN=amqp://space:space_pwd@amqp:5672/%2f/history_sent
            - MESSENGER_JOB_DONE_DSN=amqp://space:space_pwd@amqp:5672/%2f/job_done
            - SPACE_JWT_PASSPHRASE=ajpQepxkoX7LTCP3m44g8GKLd8FHLgAdp86Jn7nTJNgm9dXgjfb68mnG7f7xH3cA
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/messages/private.pem
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY_PASSPHRASE=GQRNrqcX9fkAAHSg8P6MKktykTh399
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/messages/public.pem
            - PHP_XDEBUG_HOST=172.16.1.1
