version: "3.7"
networks:
    backend: ~
    bdd: ~
    amqp: ~
volumes:
    caddy_data:
    caddy_config:
services:
    mercure:
        image: dunglas/mercure:latest
        ports:
            - 8181:8181
        environment:
            SERVER_NAME: ':8181'
            MERCURE_PUBLISHER_JWT_ALG: 'HS256'
            MERCURE_SUBSCRIBER_JWT_ALG: 'HS256'
            PUBLISH_ALLOWED_ORIGINS: '*'
            ALLOW_ANONYMOUS: 1
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins https://localhost
                anonymous
            CORS_ALLOWED_ORIGINS: '*'
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - backend
    db:
        build:
            context: ./build.dev/mongo
        ports:
            - 27017:27017
        networks:
            - bdd
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin_space
            MONGO_INITDB_ROOT_PASSWORD: space_pwd
            MONGO_INITDB_DATABASE: space
        volumes:
            - ./var/mongo:/var/lib/mongodb
    amqp:
        build:
            context: ./build.dev/rabbitmq
        ports:
            - 8080:8080
            - 5672:5672
        environment:
            RABBITMQ_USERNAME: space
            RABBITMQ_PASSWORD: space_pwd
        networks:
            - amqp
    php:
        build:
            context: ./build.dev/php
        privileged: true
        expose:
            - 9000
        networks:
            - bdd
            - backend
            - amqp
        links:
            - db
        volumes:
            - ./appliance/:/var/www/space
        environment:
            - MAILER_TRANSPORT=smtp
            - MAILER_SENDER_NAME=Teknoo Space App
            - MONGODB_NAME=space
            - SPACE_CLUSTER_ISSUER=lets-encrypt
            - SPACE_HOSTNAME=localhost
            - SPACE_KUBERNETES_CLIENT_TIMEOUT=3
            - SPACE_JOB_ROOT=/tmp
            - SPACE_KUBERNETES_CLIENT_VERIFY_SSL=1
            - SPACE_KUBERNETES_CLUSTER_ENV=prod
            - SPACE_KUBERNETES_CLUSTER_NAME=Teknoo Space Hydrogen
            - SPACE_KUBERNETES_CLUSTER_TYPE=kubernetes
            - SPACE_KUBERNETES_CREATE_TOKEN=fooBar
            - SPACE_KUBERNETES_ROOT_NAMESPACE=space-client-
            - SPACE_OCI_GLOBAL_REGISTRY_USERNAME=spaceuser
            - SPACE_OCI_REGISTRY_IMAGE=registry:latest
            - SPACE_OCI_REGISTRY_PVC_SIZE=4Gi
            - SPACE_OCI_REGISTRY_TLS_SECRET=registry-certs
            - SPACE_PING_FILE=var/ping_file
            - SPACE_PING_SECONDS=60
            - SPACE_STORAGE_CLASS=nfs.csi.k8s.io
            - SPACE_STORAGE_DEFAULT_SIZE=3Gi
            - SPACE_CODE_SUBSCRIPTION_REQUIRED=1
            - PHP_BLACKFIRE_SERVER=blackfire
            - MAILER_FORBIDDEN_WORDS=.ru,dating,ericjones,SpellPerfect,bit.ly,love,sex,btc,crypto,misspelled,http://,https://bul.tc
            - TEKNOO_PAAS_SECURITY_ALGORITHM=rsa
            - TEKNOO_PAAS_SECURITY_PRIVATE_KEY=/var/www/space/var/keys/private.pem
            - TEKNOO_PAAS_SECURITY_PUBLIC_KEY=/var/www/space/var/keys/public.pem
            - SPACE_JWT_SECRET_KEY=%kernel.project_dir%/var/jwt/private.pem
            - SPACE_JWT_PUBLIC_KEY=%kernel.project_dir%/var/jwt/public.pem
            - SPACE_JWT_TTL=31104000
    httpd:
        build:
            context: build.dev/httpd
        ports:
            - 80:80
            - 443:443
        networks:
            - backend
        volumes:
            - ./appliance/public:/var/www/space/public
    blackfire:
        image: blackfire/blackfire:2
        ports: ["8307"]
        networks:
            - backend