space_api_v1_my_settings:
    path: '/my-settings'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.my_settings'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\User\SpaceUserType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceUserLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceUser'
        template: '@@TeknooSpace/api/User/settings.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceUserWriter'
