# Login route shipped by East Common (`check_path` of the `json_login` authenticator), with the template of Space
_east_common_api_v1_login:
    resource: '@TeknooEastCommonBundle/config/jwt_api_login_routing.yaml'
    schemes: ['https']
    defaults:
        tokenTemplate: '@@TeknooSpace/api/Jwt/jwt.token.json.twig'
