framework:
    messenger:
        transports:
            new_job:
                dsn: '%teknoo.space.messenger.dsn.new_job%'
                retry_strategy:
                    max_retries: 0
            history_sent: '%teknoo.space.messenger.dsn.history_sent%'
            job_done: '%teknoo.space.messenger.dsn.job_done%'
            execute_job:
                dsn: '%teknoo.space.messenger.dsn.execute_job%'
                # default configuration
                retry_strategy:
                    max_retries: 0
