services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    teknoo.space.endpoint.subscription:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\Subscription'
            - '@service_container'

    teknoo.space.endpoint.code_generator:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\FormWithoutObject'
            - '@service_container'

    teknoo.space.endpoint.job.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\JobStart'
            - '@service_container'

    teknoo.space.endpoint.job.restart:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\JobRestart'
            - '@service_container'

    teknoo.space.endpoint.job.pending:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\JobPending'
            - '@service_container'

    teknoo.space.endpoint.job.get:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\JobGet'
            - '@service_container'

    teknoo.space.endpoint.job.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\JobList'
            - '@service_container'

    teknoo.space.endpoint.my_settings:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\UserMySettings'
            - '@service_container'

    teknoo.space.endpoint.my_settings.jwt_token:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\UserGetJwtToken'
            - '@service_container'

    teknoo.space.endpoint.account.settings:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountEditSettings'
            - '@service_container'

    teknoo.space.endpoint.account.settings_without_steps:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountEditSettings:without-steps'
            - '@service_container'

    teknoo.space.endpoint.account.status:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountStatus'
            - '@service_container'

    teknoo.space.endpoint.account_cluster.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountClusterList'
            - '@service_container'

    teknoo.space.endpoint.account_cluster.edit:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountClusterEdit'
            - '@service_container'

    teknoo.space.endpoint.account_cluster.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountClusterNew'
            - '@service_container'

    teknoo.space.endpoint.account_cluster.delete:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AccountClusterDelete'
            - '@service_container'

    teknoo.space.endpoint.admin.account.status:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\AdminAccountStatus'
            - '@service_container'

    teknoo.space.endpoint.admin.account.edit_without_steps:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\EditAccountEndPointInterface:without-steps'
            - '@service_container'

    teknoo.space.endpoint.admin.account.environment.reinstall:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Kubernetes\Recipe\Plan\AccountEnvironmentReinstall'
            - '@service_container'

    teknoo.space.endpoint.admin.account.registry.reinstall:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Kubernetes\Recipe\Plan\AccountRegistryReinstall'
            - '@service_container'

    teknoo.space.endpoint.admin.account.quota.refresh:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Kubernetes\Recipe\Plan\AccountRefreshQuota'
            - '@service_container'

    teknoo.space.endpoint.project.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\ProjectList'
            - '@service_container'

    teknoo.space.endpoint.project.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\ProjectNew'
            - '@service_container'

    teknoo.space.endpoint.project.edit:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\EditProjectEndPointInterface'
            - '@service_container'

    teknoo.space.endpoint.project.refresh_credentials:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\RefreshProjectCredentials'
            - '@service_container'

    teknoo.space.endpoint.dashboard:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\Dashboard'
            - '@service_container'

    teknoo.space.endpoint.dashboard_frame:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\DashboardFrame'
            - '@service_container'

    teknoo.space.endpoint.contact:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\Space\Recipe\Plan\Contact'
            - '@service_container'
