parameters:
    locale: 'en'

    languages:
        - 'fr'
        - 'en'

    teknoo.east.common.bundle.allowed_forms: {
        "@TeknooEastCommon/AdminUser/list.html.twig" : {
            "user_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\UserSearchType"
        },
        "@TeknooEastPaas/AdminAccount/list.html.twig": {
            "account_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\AccountSearchType"
        },
        "@TeknooEastPaas/AdminProject/list.html.twig": {
            "project_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\ProjectSearchType"
        },
        "@TeknooEastPaas/Project/list.html.twig": {
            "project_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\ProjectSearchType"
        },
        "@TeknooEastPaas/AdminJob/list.html.twig": {
            "job_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\JobSearchType"
        },
        "@TeknooEastPaas/Job/list.html.twig": {
            "job_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\JobSearchType"
        },
        "@TeknooEastPaas/Job/list.json.twig": {
            "job_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\JobSearchType"
        },
        "@TeknooEastCommon/AdminMedia/list.html.twig": {
            "media_search": "Teknoo\\Space\\Infrastructures\\Symfony\\Form\\Type\\Search\\MediaSearchType"
        },
    }

    teknoo.space.default.code.subscription.required: true
    teknoo.space.default.mailer.forbidden_words: ''
    teknoo.space.default.mailer.sender_address: ''
    teknoo.space.default.mailer.sender_name: ''
    teknoo.space.default.mercure.publishing_enabled: true
    teknoo.space.default.messenger.dsn: 'in-memory://'
    teknoo.space.default.new_job.waiting_time: 5
    teknoo.space.default.support.contact: ''
    teknoo.space.default.user.2fa.provider: 'google'

    teknoo.east.common.admin.rendering.clean_html: true
    teknoo.east.common.rendering.clean_html: true

    teknoo.east.paas.admin.rendering.clean_html: true
    teknoo.east.paas.job_unit.use_hierarchical_namespaces: true
    teknoo.east.paas.rendering.clean_html: true
    teknoo.east.paas.symfony.history.prefer-real-date: true
    teknoo.east.paas.symfony.prepare-job.prefer-real-date: true

    teknoo.space.assets.version: '2024.01.10'

    teknoo.space.jwt.enable_in-query: '%env(bool:SPACE_JWT_ENABLE_IN_QUERY)%'

    teknoo.space.mercure.publishing_enabled: '%env(default:teknoo.space.default.mercure.publishing_enabled:SPACE_MERCURE_PUBLISHING_ENABLED)%'

    teknoo.space.messenger.dsn.execute_job: '%env(string:default:teknoo.space.default.messenger.dsn:MESSENGER_EXECUTE_JOB_DSN)%'
    teknoo.space.messenger.dsn.history_sent: '%env(string:default:teknoo.space.default.messenger.dsn:MESSENGER_HISTORY_SENT_DSN)%'
    teknoo.space.messenger.dsn.job_done: '%env(string:default:teknoo.space.default.messenger.dsn:MESSENGER_JOB_DONE_DSN)%'
    teknoo.space.messenger.dsn.new_job: '%env(string:default:teknoo.space.default.messenger.dsn:MESSENGER_NEW_JOB_DSN)%'

    teknoo.space.oauth.server.type: '%env(string:OAUTH_SERVER_TYPE)%'
    teknoo.space.oauth.provider.class: ''

    teknoo.space.ping_file: '%env(SPACE_PING_FILE)%'
    teknoo.space.ping_seconds: '%env(int:SPACE_PING_SECONDS)%'

    teknoo.space.prefer-real-date: true

    teknoo.space.rendering.clean_html: true

    teknoo.space.support.contact: '%env(string:default:teknoo.space.default.support.contact:SPACE_SUPPORT_CONTACT)%'

    teknoo.space.user.2fa.provider: '%env(string:default:teknoo.space.default.user.2fa.provider:SPACE_2FA_PROVIDER)%'
    teknoo.space.user.2fa.routes:
        google_authenticator:
            enable: '_teknoo_common_2fa_google_enable'
            disable: '_teknoo_common_2fa_google_disable'
            qrcode: '_teknoo_common_2fa_google_qrcode'
            validate: '_teknoo_common_2fa_google_validate'
        generic:
            enable: '_teknoo_common_2fa_totp_enable'
            disable: '_teknoo_common_2fa_totp_disable'
            qrcode: '_teknoo_common_2fa_totp_qrcode'
            validate: '_teknoo_common_2fa_totp_validate'
