imports:
    - { resource: parameters.yaml }
    - { resource: disabled_services.yaml }
    - { resource: endpoints.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $adminRoleName: 'ROLE_ADMIN'
            $codeGeneratorSalt: '%env(SPACE_CODE_GENERATOR_SALT)%'
            $spaceDashboardRoute: 'space_dashboard'
            $spaceUpdatePasswordRoute: 'space_update_password'
            $enableCodeRestriction: '%env(default:teknoo.space.default.code.subscription.required:SPACE_CODE_SUBSCRIPTION_REQUIRED)%'
            $default2FAProviderName: '%teknoo.space.user.2fa.provider%'
            $routesFor2FAByProviders: '%teknoo.space.user.2fa.routes%'
            $planCatalog : '@teknoo.space.subscription_plan_catalog'

    ###################
    # Generic

    Teknoo\Space\App\:
        resource: '../src/*'
        exclude: '../src/{patch,DependencyInjection,Kernel.php}'

    Teknoo\Space\Infrastructures\Symfony\:
        resource: '../infrastructures/Symfony/*'

    Teknoo\Space\Infrastructures\Twig\Extension\CollectionSerializing:
        class: 'Teknoo\Space\Infrastructures\Twig\Extension\CollectionSerializing'
        arguments:
            $serializer: '@serializer'
        tags:
            - { name: twig.extension }

    Teknoo\Space\Infrastructures\Twig\Extension\ObjectSerializing:
        class: 'Teknoo\Space\Infrastructures\Twig\Extension\ObjectSerializing'
        arguments:
            $serializer: '@serializer'
        tags:
            - { name: twig.extension }

    Teknoo\Space\Infrastructures\Twig\Extension\:
        resource: '../infrastructures/Twig/Extension/*'
        exclude:
            - '../infrastructures/Twig/Extension/CollectionSerializing'
            - '../infrastructures/Twig/Extension/ObjectSerializing'
            - '../infrastructures/Twig/Extension/MFARoutesFinder/'
        tags:
            - { name: twig.extension }

    Teknoo\Space\Infrastructures\Symfony\Security\Voter\:
        resource: '../infrastructures/Symfony/Security/Voter/'
        tags: ['security.voter']

    ##################
    # Domain interface implementation
    Teknoo\Space\Contracts\Recipe\Step\Job\CallNewJobInterface:
        alias: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\CallNewJob'
        public: true

    Teknoo\Space\Contracts\Recipe\Step\Job\NewJobNotifierInterface:
        alias: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\NewJobNotifier'
        public: true

    Teknoo\Space\Contracts\Recipe\Step\Subscription\LoginUserInterface:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Subscription\LoginUser'
        public: true
        arguments:
            - '@Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface'
        calls:
            - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
            - ['setRouter', ['@router']]

    Teknoo\Space\Contracts\Recipe\Step\Job\FetchJobIdFromPendingInterface:
        alias: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Mercure\FetchJobIdFromPending'
        public: true

    Symfony\Component\HttpClient\EventSourceHttpClient:
        class: 'Symfony\Component\HttpClient\EventSourceHttpClient'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Mercure\FetchJobIdFromPending:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Mercure\FetchJobIdFromPending'
        public: true
        bind:
            $topicRoute: 'space_job_new_pending'
            $sseClient: '@Symfony\Component\HttpClient\EventSourceHttpClient'
            $mercureEnabled: '%teknoo.space.mercure.publishing_enabled%'

    Teknoo\Space\Contracts\Recipe\Step\User\JwtCreateTokenInterface:
        alias: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\User\JwtCreateToken'
        public: true

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\User\JwtCreateToken:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\User\JwtCreateToken'
        public: true
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'
            - '@security.token_storage'

    ###################
    # Generic
    Teknoo\Space\Infrastructures\Symfony\Service\Account\CodeGenerator:
        class: 'Teknoo\Space\Infrastructures\Symfony\Service\Account\CodeGenerator'

    #############
    # Mercure
    Teknoo\Space\Infrastructures\Symfony\Mercure\JobUrlPublisher:
        class: 'Teknoo\Space\Infrastructures\Symfony\Mercure\JobUrlPublisher'
        arguments:
            - '@Symfony\Component\Mercure\HubInterface'
            - '%teknoo.space.mercure.publishing_enabled%'

    Teknoo\Space\Infrastructures\Symfony\Mercure\JobErrorPublisher:
        class: 'Teknoo\Space\Infrastructures\Symfony\Mercure\JobErrorPublisher'
        arguments:
            - '@Symfony\Component\Mercure\HubInterface'
            - '%teknoo.space.mercure.publishing_enabled%'

    Teknoo\Space\Infrastructures\Symfony\Mercure\Notifier\JobError:
        class: 'Teknoo\Space\Infrastructures\Symfony\Mercure\Notifier\JobError'
        arguments:
            - '@Teknoo\Space\Infrastructures\Symfony\Mercure\JobErrorPublisher'
            - '@router'
            - 'space_job_new_pending'

    ############
    # Messenger
    Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\HistorySentHandler:
        class: 'Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\HistorySentHandler'
        arguments:
            - '@Teknoo\East\FoundationBundle\Messenger\Executor'
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\AddHistoryInterface'
            - '@Teknoo\East\Foundation\Http\Message\MessageFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
            - '@Teknoo\East\FoundationBundle\Messenger\Client'
            - '@logger'
            - '@Teknoo\East\Paas\Contracts\Security\EncryptionInterface'
        tags:
            - 'messenger.message_handler'

    Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\NewJobHandler:
        class: 'Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\NewJobHandler'
        arguments:
            - '@Teknoo\East\FoundationBundle\Messenger\Executor'
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\NewJobInterface'
            - '@Teknoo\East\Foundation\Http\Message\MessageFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
            - '@Teknoo\East\FoundationBundle\Messenger\Client'
            - '@logger'
            - '@Teknoo\Space\Infrastructures\Symfony\Mercure\Notifier\JobError'
            - '@Teknoo\East\Paas\Contracts\Security\EncryptionInterface'
            - '@Teknoo\East\Foundation\Time\SleepServiceInterface'
            - '%env(default:teknoo.space.default.new_job.waiting_time:SPACE_NEW_JOB_WAITING_TIME)%'
        tags:
            - 'messenger.message_handler'

    Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\RunJobHandler:
        class: 'Teknoo\Space\Infrastructures\Symfony\Messenger\Handler\RunJobHandler'
        arguments:
            - '@Teknoo\East\FoundationBundle\Messenger\Executor'
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\RunJobInterface'
            - '@Teknoo\East\Foundation\Http\Message\MessageFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
            - '@Teknoo\East\FoundationBundle\Messenger\Client'
            - '@logger'
            - '@Teknoo\East\Paas\Contracts\Security\EncryptionInterface'
        tags:
            - 'messenger.message_handler'

    ########################
    # Recipe
    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\CallNewJob:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\CallNewJob'
        public: true
        arguments:
            - '@messenger.routable_message_bus'
            - '@Teknoo\East\Paas\Contracts\Security\EncryptionInterface'


    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\NewJobNotifier:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\NewJobNotifier'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Symfony\Mercure\JobUrlPublisher'
            - '@router'
            - 'space_job_new_pending'
            - 'space_job_list'
            - '@logger'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\JobUpdaterNotifier:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\JobUpdaterNotifier'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Symfony\Mercure\JobUrlPublisher'
            - '@router'
            - 'space_job_new_pending'
            - 'space_job_get'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\JobErrorNotifier:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\JobErrorNotifier'
        public: true
        arguments:
            - '@Teknoo\Space\Infrastructures\Symfony\Mercure\Notifier\JobError'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\PersistJobVar:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Job\PersistJobVar'
        public: true
        arguments:
            - '@Teknoo\Space\Writer\PersistedVariableWriter'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\AccessControl\ObjectAccessControl:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\AccessControl\ObjectAccessControl'
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\AccessControl\ListObjectsAccessControl:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\AccessControl\ListObjectsAccessControl'
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\User\LoadUserInSpace:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\User\LoadUserInSpace'
        arguments:
            - '@security.token_storage'
            - '@Teknoo\Space\Loader\Meta\SpaceUserLoader'
            - '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        public: true

    Teknoo\Space\Contracts\Recipe\Step\Contact\SendEmailInterface:
        alias: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Email\SendEmail'
        public: true

    Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Email\SendEmail:
        class: 'Teknoo\Space\Infrastructures\Symfony\Recipe\Step\Email\SendEmail'
        arguments:
            - '@Symfony\Component\Mailer\MailerInterface'
            - '%env(default:teknoo.space.default.mailer.sender_name:MAILER_SENDER_NAME)%'
            - '%env(default:teknoo.space.default.mailer.sender_address:MAILER_SENDER_ADDRESS)%'
            - '%env(default:teknoo.space.default.mailer.forbidden_words:MAILER_FORBIDDEN_WORDS)%'
            - {
                  support: '%teknoo.space.support.contact%'
            }
        public: true

    ####################
    # Form
    Teknoo\Space\Infrastructures\Doctrine\Form\UserData\UserDataType:
        class: 'Teknoo\Space\Infrastructures\Doctrine\Form\UserData\UserDataType'
        arguments:
            - '@Teknoo\East\Common\Doctrine\Writer\ODM\MediaWriter'
        tags:
            - {name: form.type}

    #####################
    # Login
    Teknoo\East\CommonBundle\EndPoint\ConnectEndPoint:
        class: 'Teknoo\East\CommonBundle\EndPoint\ConnectEndPoint'
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            - '%teknoo.space.oauth.server.type%'
            - [ 'read_user' ]
        calls:
            - [ 'setResponseFactory', [ '@Psr\Http\Message\ResponseFactoryInterface' ] ]
            - [ 'setRouter', [ '@router' ] ]
        public: true

    Teknoo\East\CommonBundle\Contracts\Security\Authenticator\UserConverterInterface:
        class: 'Teknoo\Space\Infrastructures\Symfony\Security\Authenticator\UserConverter'
