services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appHostname: '%teknoo.space.hostname%'
            $defaultClusterName: '%teknoo.space.kubernetes.cluster.default_name%'
            $defaultClusterType: '%teknoo.space.kubernetes.cluster.default_type%'
            $defaultClusterAddress: '%teknoo.space.kubernetes.master%'
            $defaultClusterEnv: '%teknoo.space.kubernetes.cluster.default_env%'
            $testTransport: '@zenstruck_messenger_test.transport_registry'
            $cacheExpiredLinks: '@security.authenticator.cache.expired_links'

    Teknoo\Space\Tests\Behat\GetTokenStorageService:
        public: true
        arguments:
            - '@?security.token_storage'

    Teknoo\Space\Tests\Behat\:
        resource: '../tests/Behat/*'
        exclude: '../tests/Behat/{GetTokenStorageService.php}'

    Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorageFactory: ~

    Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\SpaceSubscriptionType:
        public: true
        tags:
            - {name: form.type}

    doctrine_mongodb.messenger.event_subscriber.doctrine_clear_document_manager:
        class: 'Teknoo\Space\Tests\Behat\ODM\DoctrineClearEntityManagerWorkerSubscriber'
        tags:
            - {name: kernel.event_subscriber}
