space_api_admin_project_new:
    path: '/project/new/{accountId}'
    methods: ['POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.new.project'
        accountKey: 'constructorArguments'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: true
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceProject'
        route: 'space_api_admin_project_edit'
        template: '@@TeknooEastPaas/api/Project/item.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'

space_api_admin_project_edit:
    path: '/project/{id}'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.edit.project'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: true
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceProject'
        route: 'space_api_admin_project_edit'
        template: '@@TeknooEastPaas/api/Project/item.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'

space_api_admin_project_list:
    path: '/projects'
    methods: ['GET', 'POST']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        api: 'json'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooEastPaas/api/Project/list.json.twig'
