space_api_v1_admin_project_new:
    path: '/account/{accountId}/project/new'
    methods: ['POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.new.project'
        accountKey: 'constructorArguments'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: true
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceProject'
        route: 'space_api_v1_admin_project_edit'
        template: '@@TeknooSpace/api/Project/item.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        clusterCatalog: '@teknoo.space.clusters_catalog'

space_api_v1_admin_project_edit:
    path: '/account/{accountId}/project/{id}'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.edit.project'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: true
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceProject'
        route: 'space_api_v1_admin_project_edit'
        template: '@@TeknooSpace/api/Project/item.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        clusterCatalog: '@teknoo.space.clusters_catalog'

space_api_v1_admin_project_edit_variables:
    path: '/account/{accountId}/project/{id}/variables'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.project.edit'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\VarsType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        populateFormOptions: true
        template: '@@TeknooSpace/api/Project/variables.json.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        clusterCatalog: '@teknoo.space.clusters_catalog'

space_api_v1_admin_project_refresh_credentials:
    path: '/account/{accountId}/project/{id}/refresh-credentials'
    methods: ['POST']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.project.refresh_credentials'
        api: 'json'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        route: 'space_api_v1_admin_project_edit'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"
        clusterCatalog: '@teknoo.space.clusters_catalog'

space_api_v1_admin_account_project_list:
    path: '/account/{accountId}/projects'
    methods: ['GET', 'POST']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.project.list'
        api: 'json'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooSpace/api/Project/list.json.twig'

space_api_v1_admin_project_list:
    path: '/projects'
    methods: ['GET', 'POST']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        api: 'json'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooSpace/api/Project/list.json.twig'

space_api_v1_admin_project_delete:
    path: '/account/{accountId}/project/{id}/delete'
    methods: ['POST', 'DELETE']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        api: 'json'
        deleter: '@teknoo.space.deleting.space_project'
        errorTemplate: '@@TeknooEastCommon/Error/default.json.twig'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectViewKey: 'projectInstance'
        template: '@@TeknooSpace/api/Project/deleted.json.twig'

