admin_common:
    resource: '@TeknooEastCommonBundle/Resources/config/admin_routing.yaml'
    prefix: '/admin'

2fa_common:
    resource: '@TeknooEastCommonBundle/Resources/config/2fa_routing.yaml'
    prefix: '/'

common_assets:
    resource: '@TeknooEastCommonBundle/Resources/config/assets_routing.yaml'
    prefix: '/build'

common_user_recovery:
    resource: '@TeknooEastCommonBundle/Resources/config/user_recovery_routing.yaml'
    prefix: '/account'

common:
    resource: '@TeknooEastCommonBundle/Resources/config/routing.yaml'
    prefix: '/'

