oauth_connect_gitlab_login:
    path: '/oauth/gitlab/login'
    defaults:
        _controller: 'Teknoo\East\CommonBundle\EndPoint\ConnectEndPoint'

oauth_connect_gitlab_check:
    path: '/oauth/gitlab/check'
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        template: '@@TeknooEastPaas/Admin/index.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        _oauth_client_key: gitlab