_teknoo_paas_admin_account_list:
    path: '/admin/accounts'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        template: '@@TeknooEastPaas/AdminAccount/list.html.twig'

_teknoo_paas_admin_account_edit:
    path: '/admin/account/edit/{id}'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.edit.account'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\AdminSpaceAccountType'
        formOptions:
            "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"
            namespace_in_readonly: true
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        template: '@@TeknooEastPaas/AdminAccount/edit.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceAccountWriter'

_teknoo_paas_admin_account_new:
    path: '/admin/account/new'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.new.account'
        accountKey: 'constructorArguments'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\AdminSpaceAccountType'
        formOptions: { "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%" }
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceAccount'
        route: '_teknoo_paas_admin_account_edit'
        template: '@@TeknooEastPaas/AdminAccount/new.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceAccountWriter'

_teknoo_paas_admin_account_delete:
    path: '/admin/account/delete/{id}'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.space.deleting.space_account'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        route: '_teknoo_paas_admin_account_list'

space_admin_account_edit_variables:
    path: '/admin/account/variables/{id}'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.edit.account'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\VarsType'
        formOptions: {}
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        template: '@@TeknooEastPaas/AdminAccount/variables.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceAccountWriter'

space_admin_account_reinstall:
    path: '/admin/account/reinstall/{id}'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.space.endpoint.admin.account.reinstall'
        allowEmptyCredentials: true
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        route: '_teknoo_paas_admin_account_edit'

space_admin_account_registry_reinstall:
    path: '/admin/account/reinstall-registry/{id}'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.space.endpoint.admin.account.registry-reinstall'
        allowEmptyCredentials: true
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        route: '_teknoo_paas_admin_account_edit'
