_teknoo_paas_admin_job_list:
    path: '/admin/jobs'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderColumn: 'updatedAt'
        defaultOrderDirection: 'DESC'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        template: '@@TeknooEastPaas/AdminJob/list.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

_teknoo_paas_admin_job_delete:
    path: '/admin/job/delete/{id}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.paas.deleting.job'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        nextRoute: 'admin_job_list'
        route: '_teknoo_paas_admin_job_list'

space_admin_new_job:
    path: '/admin/project/{projectId}/new-job'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.new'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/AdminJob/new.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

space_admin_restart_job:
    path: '/admin/project/{projectId}/restart-job/{jobId}'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.restart'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formActionRoute: 'space_admin_new_job'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/AdminJob/new.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

space_admin_get_job:
    path: '/admin/job/{id}'
    methods: [ 'GET', 'POST', 'PUT' ]
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.get'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        objectViewKey: 'jobInstance'
        template: '@@TeknooEastPaas/AdminJob/get.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"
