space_subscription:
    path: '/account/subscription'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.subscription'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\SpaceSubscriptionType'
        formOptions:
            doctrine_type: "%teknoo.east.common.form_type.doctrine.class%"
        objectClass: 'Teknoo\Space\Object\DTO\SpaceSubscription'
        template: '@@TeknooSpace/Account/subscription.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"
        clusterCatalog: '@teknoo.space.clusters_catalog'
        subscriptionPlanId: "%teknoo.space.subscription.plan_default%"
