space_subscription:
    path: '/account/subscription'
    methods: ['GET', 'POST', 'PUT']
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.subscription'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\SpaceSubscriptionType'
        formOptions: { }
        objectClass: 'Teknoo\Space\Object\DTO\SpaceSubscription'
        template: '@@TeknooEastPaas/Account/subscription.html.twig'
