
space_admin_job_new:
    path: '/admin/project/{projectId}/job/new'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.new'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/AdminJob/new.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"
        clusterCatalog: '@teknoo.space.clusters_catalog'

space_admin_job_restart:
    path: '/admin/project/{projectId}/job/{jobId}/restart'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.restart'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formActionRoute: 'space_admin_job_new'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/AdminJob/new.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

space_admin_job_get:
    path: '/admin/job/{id}'
    methods: [ 'GET', 'POST', 'PUT' ]
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.job.get'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        objectViewKey: 'jobInstance'
        template: '@@TeknooEastPaas/AdminJob/get.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"
