space_account_logout:
    path: '/account/logout'
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooSpace/Account/login.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_account_login:
    path: '/account/login'
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooSpace/Account/login.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_account_autologin:
    path: '/account/auto-login'
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooSpace/Account/login.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_account_check:
    path: '/account/check'
    schemes: ['https']
    methods: ['POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooSpace/Account/index.html.twig'

space_account_settings:
    path: '/account/settings'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.account.settings'
        clusterCatalog: '@teknoo.space.clusters_catalog'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\SpaceAccountType'
        formOptions:
            enableEnvManagement: true
            doctrine_type: "%teknoo.east.common.form_type.doctrine.class%"
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceAccount'
        template: '@@TeknooSpace/Account/settings.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceAccountWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_account_edit_variables:
    path: '/account/variables'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.account.settings_without_steps'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\VarsType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceAccountLoader'
        template: '@@TeknooSpace/Account/variables.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceAccountWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_account_clusters_list:
    path: '/account/clusters'
    methods: [ 'GET' ]
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.account_cluster.list'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\AccountClusterLoader'
        template: '@@TeknooSpace/AccountCluster/list.html.twig'

space_account_clusters_edit:
    path: '/account/cluster/{id}/edit'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.account_cluster.edit'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\AccountClusterType'
        loader: '@Teknoo\Space\Loader\AccountClusterLoader'
        template: '@@TeknooSpace/AccountCluster/edit.html.twig'
        writer: '@Teknoo\Space\Writer\AccountClusterWriter'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

space_account_clusters_new:
    path: '/account/cluster/new'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.account_cluster.new'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Account\AccountClusterType'
        loader: '@Teknoo\Space\Loader\AccountClusterLoader'
        objectClass: 'Teknoo\Space\Object\Persisted\AccountCluster'
        route: 'space_account_clusters_edit'
        template: '@@TeknooSpace/AccountCluster/new.html.twig'
        writer: '@Teknoo\Space\Writer\AccountClusterWriter'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

space_account_clusters_delete:
    path: '/account/cluster/{id}/delete'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.space.endpoint.account_cluster.delete'
        accountLoader: '@Teknoo\East\Paas\Loader\AccountLoader'
        deleter: '@teknoo.space.deleting.account_cluster'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\Space\Loader\AccountClusterLoader'
        route: 'space_account_clusters_list'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"
