space_job_new:
    path: '/project/{projectId}/new-job'
    methods: ['GET', 'POST', 'PUT']
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.job.new'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        formOptions: { }
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/Job/new.html.twig'

space_job_restart:
    path: '/project/{projectId}/restart-job/{jobId}'
    methods: ['GET']
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.job.restart'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formActionRoute: 'space_job_new'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Job\NewJobType'
        formOptions: { }
        objectClass: 'Teknoo\Space\Object\DTO\NewJob'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_job_new_pending'
        template: '@@TeknooEastPaas/Job/new.html.twig'

space_job_new_pending:
    path: '/job/pending/{newJobId}'
    methods: ['GET']
    schemes: [https]
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooEastPaas/Job/pending.html.twig'

space_job_get:
    path: '/job/{id}'
    methods: [ 'GET' ]
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.job.get'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formOptions: { }
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        objectViewKey: 'jobInstance'
        template: '@@TeknooEastPaas/Job/get.html.twig'

space_job_list:
    path: '/project/view/{projectId}/jobs'
    methods: [ 'GET' ]
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.job.list'
        defaultOrderColumn: 'updatedAt'
        defaultOrderDirection: 'DESC'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        projectKey: 'Teknoo\Space\Object\DTO\SpaceProject'
        projectLoader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooEastPaas/Job/list.html.twig'

space_job_delete:
    path: '/job/delete/{id}'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.paas.deleting.job'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        route: 'space_project_list'

