space_my_settings:
    path: '/my-settings'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.my_settings'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\User\SpaceUserType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceUserLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceUser'
        template: '@@TeknooSpace/User/settings.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceUserWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_update_password:
    path: '/my-settings/update-password'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.my_settings'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\User\SpacePasswordType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceUserLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceUser'
        template: '@@TeknooSpace/User/update_password.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceUserWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_my_settings_token:
    path: '/my-settings/jwt-token'
    methods: ['GET', 'POST']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.my_settings.jwt_token'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\User\JWTConfigurationType'
        objectClass: 'Teknoo\Space\Object\DTO\JWTConfiguration'
        template: '@@TeknooSpace/User/jwt.form.html.twig'
        tokenTemplate: '@@TeknooSpace/User/jwt.token.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"
