space_support_contact:
    path: '/contact/support'
    methods: ['GET', 'POST', 'PUT']
    schemes: ['https']
    defaults:
        _controller: 'teknoo.space.endpoint.contact'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Contact\SupportType'
        objectClass: 'Teknoo\Space\Object\DTO\Contact'
        receiverAddress: 'support'
        route: 'space_support_contact_sent'
        template: '@@TeknooSpace/Contact/support.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_support_contact_sent:
    path: '/contact/support/sent'
    schemes: ['https']
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        template: '@@TeknooSpace/Contact/sent.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"
