space_project_list:
    path: '/projects/'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'teknoo.space.endpoint.project.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooEastPaas/Project/list.html.twig'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_project_edit:
    path: '/project/edit/{id}'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.project.edit'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: false
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        template: '@@TeknooEastPaas/Project/edit.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_project_edit_variables:
    path: '/project/edit/{id}/variables'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.project.edit'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\VarsType'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        populateFormOptions: true
        template: '@@TeknooEastPaas/Project/variables.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_project_edit_refresh_credentials:
    path: '/project/edit/{id}/refresh-credentials'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.space.endpoint.project.refresh_credentials'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        projectKey: 'Teknoo\East\Paas\Object\Project'
        route: 'space_project_edit'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_project_new:
    path: '/project/new'
    methods: ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.space.endpoint.project.new'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Project\SpaceProjectType'
        formOptions:
            allowEditingOfLocked: false
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        objectClass: 'Teknoo\Space\Object\DTO\SpaceProject'
        route: 'space_project_edit'
        template: '@@TeknooEastPaas/Project/new.html.twig'
        writer: '@Teknoo\Space\Writer\Meta\SpaceProjectWriter'
        cleanHtml: "%teknoo.space.rendering.clean_html%"

space_project_delete:
    path: '/project/delete/{id}'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.space.deleting.space_project'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        loader: '@Teknoo\Space\Loader\Meta\SpaceProjectLoader'
        route: 'space_project_list'
