space_support_contact:
    path: '/contact/support'
    methods: ['GET', 'POST', 'PUT']
    schemes: [https]
    defaults:
        _controller: 'teknoo.space.endpoint.contact'
        objectClass: 'Teknoo\Space\Object\DTO\Contact'
        formClass: 'Teknoo\Space\Infrastructures\Symfony\Form\Type\Contact\SupportType'
        template: '@@TeknooSpace/Contact/support.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
        formOptions: { }
        route: 'space_support_contact_sent'
        receiverAddress: '%teknoo.space.support.contact%'

space_support_contact_sent:
    path: '/contact/support/sent'
    schemes: [https]
    defaults:
        _controller: 'teknoo.east.common.endpoint.static'
        template: '@@TeknooSpace/Contact/sent.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/default.html.twig'
